import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/_Component/NavigationBar";
import Footer from "@/_Component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* navbar here */}
        <header>
          <NavigationBar/>
        </header>

        <main className="mx-auto container my-9">

        {children}
        </main>

        {/* footer */}
        <footer>
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
